#pragma once

enum BANK_TRANFER_JOURNAL_TABLE_DESC : int {
	E_SERIALNUMBER = 0,
	E_ACCOUNTID,
	E_BUSINESSID,
	E_AMOUNT,
	E_DESCRIPTION,
	E_BANKNAME,
	E_BANKCARD,
	E_POSTTIME,
	E_UPDATETIME,
	E_STATEID,
	E_ORDERNUMBER,
	E_RECHARGETYPE,
	E_FEETYPE,
	E_CARDNO,
	E_RESULTCODE,
	E_RESULTMESSAGE,
	E_LOADNO,
	E_ISAPPROVAL,
	E_APPROVALTIME,
	E_APPROVALREASON,
	E_APPROVALID,
	E_BASEAMOUNT,
	E_TYPE,
	E_OFFLINERECOURCE,
	E_OFFLINEPAYACCOUNT,
	E_OFFLINESERIALNUMBER,
	E_END
};

const char* const BANK_TRANFER_JOURNAL_TABLE = "bank_tranfer_journal";

const char* const BANK_TRANFER_JOURNAL_TABLE_COLS[E_END] = {
	"SerialNumber",
	"AccountID",
	"BusinessID",
	"Amount",
	"Description",
	"BankName",
	"BankCard",
	"PostTime",
	"UpdateTime",
	"StateID",
	"OrderNumber",
	"RechargeType",
	"FeeType",
	"CardNo",
	"ResultCode",
	"ResultMessage",
	"LoadNo",
	"IsApproval",
	"ApprovalTime",
	"ApprovalReason",
	"ApprovalID",
	"BaseAmount",
	"Type",
	"OffLineRecource",
	"OffLinePayAccount",
	"OffLineSerialNumber",
};

const char* const BANK_TRANFER_JOURNAL_TABLE_COLS_ATTR[E_END] = {
	"int(11) NOT NULL COMMENT '出入金流水号'",
	"varchar(64) COLLATE utf8_general_ci NOT NULL",
	"int(11) NOT NULL COMMENT '业务ID'",
	"decimal(18,3) COMMENT '金额'",
	"varchar(200) COLLATE utf8_general_ci NOT NULL COMMENT '说明'",
	"varchar(100) COLLATE utf8_general_ci NOT NULL",
	"varchar(50) COLLATE utf8_general_ci NOT NULL",
	"datetime DEFAULT '0000-00-00 00:00:00' NOT NULL COMMENT '提交时间'",
	"datetime DEFAULT '0000-00-00 00:00:00' NOT NULL COMMENT '更新时间'",
	"smallint(6) NOT NULL COMMENT '状态'",
	"varchar(50) COLLATE utf8_general_ci NOT NULL COMMENT '订单流水号'",
	"tinyint(4) NOT NULL",
	"tinyint(4) NOT NULL",
	"varchar(50) COLLATE utf8_general_ci NOT NULL COMMENT '身份证号'",
	"varchar(50) COLLATE utf8_general_ci NOT NULL",
	"varchar(200) COLLATE utf8_general_ci NOT NULL",
	"varchar(50) COLLATE utf8_general_ci",
	"tinyint(4) NOT NULL COMMENT '是否已审核(0未审核 1审核 2审核拒绝)'",
	"datetime DEFAULT '0000-00-00 00:00:00' COMMENT '审核时间'",
	"varchar(255) COLLATE utf8_bin COMMENT '审核原因'",
	"varchar(64) COLLATE utf8_general_ci COMMENT '审核者UserID'",
	"decimal(18,3) DEFAULT '0.000' COMMENT '基币金额'",
	"int(2) DEFAULT '1' NOT NULL COMMENT '1，线上；2线下'",
	"int(2) DEFAULT '0' NOT NULL COMMENT '线下来源:1、微信;2、支付宝；3、银行转账'",
	"varchar(64) COLLATE utf8_general_ci COMMENT '线下付款账户'",
	"varchar(128) COLLATE utf8_general_ci COMMENT '线下流水号'",
};