#pragma once

enum FOLLOW_POSITION_INFO_TABLE_DESC : int {
	E_POSITIONID = 0,
	E_ORDERID,
	E_TRADEID,
	E_USERID,
	E_LOGINNAME,
	E_CONTRACTCODE,
	E_CONTRACTNAME,
	E_DIRECTION,
	E_OPENOFFSET,
	E_VOLUME,
	E_FREZONVOLUME,
	E_TRADEPRICE,
	E_GENERATEDATE,
	E_GENERATETIME,
	E_SHADOWTRADEID,
	E_EXCHANGETRADEID,
	E_TARGETUSERID,
	E_TARGETORDERID,
	E_TARGETTRADEID,
	E_TARGETPOSITIONID,
	E_FOLLOWDIRECT,
	E_FOLLOWMULTIPLE,
	E_YESTERDAYFLAG,
	E_WORDERID,
	E_WTRADEID,
	E_WPOSITIONID,
	E_END
};

const char* const FOLLOW_POSITION_INFO_TABLE = "follow_position_info";

const char* const FOLLOW_POSITION_INFO_TABLE_COLS[E_END] = {
	"positionID",
	"orderID",
	"tradeID",
	"userID",
	"loginName",
	"contractCode",
	"contractName",
	"direction",
	"openOffset",
	"volume",
	"frezonVolume",
	"tradePrice",
	"generateDate",
	"generateTime",
	"shadowTradeID",
	"exchangeTradeID",
	"targetUserID",
	"targetOrderID",
	"targetTradeID",
	"targetPositionID",
	"followDirect",
	"followMultiple",
	"yesterdayFlag",
	"wOrderID",
	"wTradeID",
	"wPositionID",
};

const char* const FOLLOW_POSITION_INFO_TABLE_COLS_ATTR[E_END] = {
	"varchar(64) COLLATE utf8_bin NOT NULL",
	"varchar(64) COLLATE utf8_bin NOT NULL COMMENT '委托ID, 作成交信息时使用'",
	"varchar(64) COLLATE utf8_bin NOT NULL COMMENT '平仓对应的持仓ID'",
	"varchar(64) COLLATE utf8_bin NOT NULL COMMENT '帐户标识（用户ID)， 系统内部使用'",
	"varchar(64) COLLATE utf8_bin NOT NULL COMMENT '登录名'",
	"varchar(64) COLLATE utf8_bin NOT NULL COMMENT '合约ID'",
	"varchar(16) COLLATE utf8_bin NOT NULL COMMENT '合约名'",
	"char(2) DEFAULT '0' COLLATE utf8_bin NOT NULL COMMENT '买卖方向，  \"B\" (buy)表示买， \"S\" (sell)表示卖'",
	"smallint(2) DEFAULT '0' NOT NULL COMMENT '开平标志，  1 表示开仓， 2 表示平仓， 3 表示平今'",
	"int(10) DEFAULT '0' NOT NULL COMMENT '成交手数'",
	"int(10) DEFAULT '0' NOT NULL COMMENT '冻结手数'",
	"decimal(32,8) DEFAULT '0.00000000' NOT NULL COMMENT '成交价格'",
	"int(10) DEFAULT '0' NOT NULL COMMENT '成交日期'",
	"int(10) DEFAULT '0' NOT NULL COMMENT '成交时间'",
	"varchar(16) COLLATE utf8_bin NOT NULL COMMENT '成交ID'",
	"varchar(32) COLLATE utf8_bin NOT NULL COMMENT '交易所成交编号'",
	"varchar(64) COLLATE utf8_bin NOT NULL COMMENT '目标账户'",
	"varchar(64) COLLATE utf8_bin NOT NULL COMMENT '目标账户的委托ID'",
	"varchar(64) COLLATE utf8_bin NOT NULL COMMENT '目标账户的成交ID'",
	"varchar(64) COLLATE utf8_bin NOT NULL COMMENT '目标账户的持仓ID'",
	"tinyint(2) DEFAULT '0' NOT NULL COMMENT '跟单方向方向，  跟单方向    0同向，1反向'",
	"int(8) DEFAULT '1' NOT NULL COMMENT '跟单倍数'",
	"smallint(2) DEFAULT '0' NOT NULL COMMENT '0 今仓 1 昨仓'",
	"varchar(64) COLLATE utf8_bin NOT NULL COMMENT '外部系统的委托ID'",
	"varchar(64) COLLATE utf8_bin NOT NULL COMMENT '外部系统的成交ID'",
	"varchar(64) COLLATE utf8_bin NOT NULL COMMENT '外部系统的持仓ID'",
};