#pragma once

enum FOLLOW_TRADE_INFO_TABLE_DESC : int {
	E_TRADEID = 0,
	E_ORDERID,
	E_POSITIONID,
	E_USERID,
	E_LOGINNAME,
	E_CONTRACTCODE,
	E_CONTRACTNAME,
	E_DIRECTION,
	E_VOLUME,
	E_TRADEPRICE,
	E_PRICETYPE,
	E_OPENOFFSET,
	E_TURNOVER,
	E_GENERATEDATE,
	E_GENERATETIME,
	E_FOLLOWDIRECT,
	E_FOLLOWMULTIPLE,
	E_TARGETUSERID,
	E_TARGETTRADEID,
	E_TARGETORDERID,
	E_TARGETPOSITIONID,
	E_EXCHANGETRADEID,
	E_WTRADEID,
	E_WPOSITIONID,
	E_WORDERID,
	E_END
};

const char* const FOLLOW_TRADE_INFO_TABLE = "follow_trade_info";

const char* const FOLLOW_TRADE_INFO_TABLE_COLS[E_END] = {
	"tradeID",
	"orderID",
	"positionID",
	"userID",
	"loginName",
	"contractCode",
	"contractName",
	"direction",
	"volume",
	"tradePrice",
	"priceType",
	"openOffset",
	"turnOver",
	"generateDate",
	"generateTime",
	"followDirect",
	"followMultiple",
	"targetUserID",
	"targetTradeID",
	"targetOrderID",
	"targetPositionID",
	"exchangeTradeID",
	"wTradeID",
	"wPositionID",
	"wOrderID",
};

const char* const FOLLOW_TRADE_INFO_TABLE_COLS_ATTR[E_END] = {
	"varchar(64) COLLATE utf8_bin NOT NULL",
	"varchar(64) COLLATE utf8_bin NOT NULL COMMENT '委托ID, 作成交信息时使用'",
	"varchar(64) COLLATE utf8_bin NOT NULL COMMENT '平仓对应的持仓ID'",
	"varchar(64) COLLATE utf8_bin NOT NULL COMMENT '帐户标识（用户ID)， 系统内部使用'",
	"varchar(64) COLLATE utf8_bin NOT NULL COMMENT '帐户名'",
	"varchar(64) COLLATE utf8_bin NOT NULL COMMENT '合约ID'",
	"varchar(16) COLLATE utf8_bin NOT NULL COMMENT '合约名'",
	"char(2) DEFAULT '0' COLLATE utf8_bin NOT NULL COMMENT '买卖方向，  \"B\" (buy)表示买， \"S\" (sell)表示卖'",
	"int(10) DEFAULT '0' NOT NULL COMMENT '成交手数'",
	"decimal(32,8) DEFAULT '0.00000000' NOT NULL COMMENT '成交价格'",
	"char(2) COLLATE utf8_bin NOT NULL COMMENT '价格类型 M市价，L限价'",
	"smallint(2) DEFAULT '0' NOT NULL COMMENT '开平标志，  1 表示开仓， 2 表示平仓， 3 表示平今'",
	"decimal(32,8) DEFAULT '0.00000000' NOT NULL COMMENT '成交额'",
	"int(10) DEFAULT '0' NOT NULL COMMENT '成交日期'",
	"int(10) DEFAULT '0' NOT NULL COMMENT '成交时间'",
	"tinyint(2) DEFAULT '0' NOT NULL COMMENT '跟单方向    0同向，1反向'",
	"int(10) DEFAULT '1' NOT NULL COMMENT '跟单倍数'",
	"varchar(64) COLLATE utf8_bin NOT NULL COMMENT '目标账户'",
	"varchar(64) COLLATE utf8_bin NOT NULL COMMENT '目标账户成交ID'",
	"varchar(64) COLLATE utf8_bin NOT NULL COMMENT '目标账户委托ID'",
	"varchar(64) COLLATE utf8_bin NOT NULL COMMENT '目标账户持仓ID'",
	"varchar(32) COLLATE utf8_bin NOT NULL COMMENT '交易所成交编号'",
	"varchar(64) COLLATE utf8_bin NOT NULL COMMENT '外部系统的成交ID'",
	"varchar(64) COLLATE utf8_bin NOT NULL COMMENT '外部系统的持仓ID'",
	"varchar(64) COLLATE utf8_bin NOT NULL COMMENT '外部系统的委托ID'",
};