#pragma once

enum ORDER_INFO_TABLE_DESC : int {
	E_ORDERID = 0,
	E_USERID,
	E_CONTRACTID,
	E_STATE,
	E_ORDERREF,
	E_CONTRACTCODE,
	E_CONTRACTNAME,
	E_LOGINNAME,
	E_ACCOUNTNAME,
	E_SHADOWORDERID,
	E_GENERATEDATE,
	E_GENERATETIME,
	E_UPDATEDATE,
	E_UPDATETIME,
	E_PRICE,
	E_VOLUME,
	E_EFFECTEDVOLUME,
	E_DIRECTION,
	E_PRICETYPE,
	E_OPENOFFSET,
	E_AVERAGETRADEPRICE,
	E_REALSYSTEMORDERID,
	E_EXCHANGECODE,
	E_FAILREASON,
	E_FAILMSG,
	E_CLOSEPOSITIONID,
	E_FREZONMARGIN,
	E_TIMECONDITIONTYPE,
	E_ORDERFROM,
	E_OPERATORID,
	E_IP,
	E_MAC,
	E_TARGETUSERID,
	E_CANCELREASON,
	E_END
};

const char* const ORDER_INFO_TABLE = "order_info";

const char* const ORDER_INFO_TABLE_COLS[E_END] = {
	"orderID",
	"userID",
	"contractID",
	"state",
	"orderRef",
	"contractCode",
	"contractName",
	"loginName",
	"accountName",
	"shadowOrderID",
	"generateDate",
	"generateTime",
	"updateDate",
	"updateTime",
	"price",
	"volume",
	"effectedVolume",
	"direction",
	"priceType",
	"openOffset",
	"averageTradePrice",
	"realSystemOrderId",
	"exchangeCode",
	"failReason",
	"failMsg",
	"closePositionID",
	"frezonMargin",
	"timeConditionType",
	"orderFrom",
	"operatorID",
	"ip",
	"mac",
	"targetUserID",
	"cancelReason",
};

const char* const ORDER_INFO_TABLE_COLS_ATTR[E_END] = {
	"int(10) NOT NULL COMMENT ' 委托ID'",
	"varchar(64) DEFAULT '0' COLLATE utf8_bin NOT NULL COMMENT '帐户标识(用户ID)， 系统内部使用'",
	"varchar(64) DEFAULT '0' COLLATE utf8_bin NOT NULL COMMENT '合约ID'",
	"tinyint(2) DEFAULT '1' NOT NULL COMMENT ' status 委托状态 1 表示委托已发送到服务器；2委托创建成功(委托已在交易交易所创建成功)；3委托全部生效；4委托部分生效，剩余部分还在委托队列中；5委托部分生效，剩余委托被用户撤销；5委托部分生效，剩余委托被系统撤销；6委托未生效，用户撤销；7委托未生效，被系统撤销。'",
	"varchar(64) COLLATE utf8_bin NOT NULL COMMENT '当委托未生效时,客户端需要唯一标示该委托,客户端生成一个唯一编码,使用该编码进行标识'",
	"varchar(16) COLLATE utf8_bin NOT NULL COMMENT '合约代码'",
	"varchar(16) COLLATE utf8_bin NOT NULL",
	"varchar(32) COLLATE utf8_bin NOT NULL",
	"varchar(32) COLLATE utf8_bin NOT NULL COMMENT ' 帐户名'",
	"varchar(32) COLLATE utf8_bin NOT NULL COMMENT '影子订单编号， 客户端显示使用'",
	"int(10) DEFAULT '0' NOT NULL COMMENT '委托创建日期'",
	"int(10) DEFAULT '0' NOT NULL COMMENT '委托创建时间'",
	"int(10) DEFAULT '0' NOT NULL COMMENT ' 委托状态最后更新日期'",
	"int(10) DEFAULT '0' NOT NULL COMMENT '委托状态最后更新时间'",
	"decimal(32,8) DEFAULT '0.00000000' NOT NULL COMMENT '委托价格'",
	"int(10) DEFAULT '0' NOT NULL COMMENT '委托手数'",
	"int(10) DEFAULT '0' NOT NULL COMMENT '已生效手数'",
	"char(2) DEFAULT '0' COLLATE utf8_bin NOT NULL COMMENT '买卖方向，  \"B\" (buy)表示买， \"S\" (sell)表示卖'",
	"char(2) DEFAULT '0' COLLATE utf8_bin NOT NULL COMMENT '价格类型，   \"M\"=77 (market)表示市价， \"L\"=76 (limit)表示限价'",
	"tinyint(2) DEFAULT '0' NOT NULL COMMENT '开平标志，  1 表示开仓， 2 表示平仓， 3 表示平今'",
	"decimal(32,8) DEFAULT '0.00000000' NOT NULL COMMENT '成交均价'",
	"varchar(24) COLLATE utf8_bin NOT NULL COMMENT '实盘委托编号'",
	"varchar(16) COLLATE utf8_bin NOT NULL COMMENT ' 交易所 ID'",
	"int(10) DEFAULT '0' NOT NULL COMMENT '委托失败原因'",
	"varchar(64) COLLATE utf8_bin NOT NULL COMMENT '失败信息'",
	"varchar(64) DEFAULT '0' COLLATE utf8_bin NOT NULL COMMENT ' 平仓目标ID, 平指定持仓时使用'",
	"decimal(16,8) DEFAULT '0.00000000' NOT NULL COMMENT '外盘时候考虑交易汇率变化，这里有个记录值，只供系统计算使用，如果撤单能按照原值退回，按系统基币计算值'",
	"tinyint(1) NOT NULL COMMENT '时间有效类型，0当日有效，1交割日前有效'",
	"int(2) DEFAULT '0' NOT NULL COMMENT '0PC，1app，2mc，3rc，4条件单(tc)，5止盈止损(TC)，6风控模块(TC)，7修正持仓，8程序单，9修正状态,10自动止盈止损（PC）'",
	"varchar(64) COLLATE utf8_bin NOT NULL COMMENT '操作者，实际上就是管理员id或机构ID'",
	"varchar(32) COLLATE utf8_bin NOT NULL COMMENT '客户端下单的IP'",
	"varchar(64) COLLATE utf8_bin NOT NULL COMMENT '客户端下单的MAC地址'",
	"varchar(64) COLLATE utf8_bin NOT NULL COMMENT '目标账户'",
	"tinyint(2) DEFAULT '0' NOT NULL COMMENT '0客户撤单，1系统风控撤单'",
};