#pragma once

enum POSITION_INFO_TABLE_DESC : int {
	E_POIN_POSITIONID = 0,
	E_POIN_TRADEID,
	E_POIN_USERID,
	E_POIN_CONTRACTID,
	E_POIN_VOLUME,
	E_POIN_FREZONVOLUME,
	E_POIN_TRADEPRICE,
	E_POIN_CONTRACTNAME,
	E_POIN_ACCOUNTNAME,
	E_POIN_GENERATEDATE,
	E_POIN_GENERATETIME,
	E_POIN_DIRECTION,
	E_POIN_SHADOWORDERID,
	E_POIN_OPENOFFSET,
	E_POIN_EXCHANGETRADEID,
	E_POIN_SHADOWTRADEID,
	E_POIN_YESTERDAYFLAG,
	E_POIN_CONTRACTMARGIN,
	E_POIN_SYSTEMMARGIN,
	E_POIN_PRESETTLEMENTPRICE,
	E_POIN_SETTLEMENTPRICE,
	E_POIN_ORDERID,
	E_POIN_TARGETUSERID,
	E_POIN_END
};

const char* const POSITION_INFO_TABLE = "position_info";

const char* const POSITION_INFO_TABLE_COLS[E_POIN_END] = {
	"positionID",
	"tradeID",
	"userID",
	"contractID",
	"volume",
	"frezonVolume",
	"tradePrice",
	"contractName",
	"accountName",
	"generateDate",
	"generateTime",
	"direction",
	"shadowOrderID",
	"openOffset",
	"exchangeTradeID",
	"shadowTradeID",
	"yesterdayFlag",
	"contractMargin",
	"systemMargin",
	"preSettlementPrice",
	"settlementPrice",
	"orderID",
	"targetUserID",
};

const char* const POSITION_INFO_TABLE_COLS_ATTR[E_POIN_END] = {
	"varchar(64) COLLATE utf8_bin NOT NULL",
	"varchar(64) COLLATE utf8_bin NOT NULL COMMENT '平仓对应的持仓ID'",
	"varchar(64) DEFAULT '0' COLLATE utf8_bin NOT NULL COMMENT '帐户标识（用户ID)， 系统内部使用'",
	"varchar(64) DEFAULT '0' COLLATE utf8_bin NOT NULL COMMENT '合约ID'",
	"int(10) DEFAULT '0' NOT NULL COMMENT '成交手数'",
	"int(10) DEFAULT '0' NOT NULL COMMENT '冻结持仓数量，平指定持仓使用'",
	"decimal(32,8) DEFAULT '0.00000000' NOT NULL COMMENT '成交价格'",
	"varchar(16) COLLATE utf8_bin NOT NULL COMMENT '合约名'",
	"varchar(32) COLLATE utf8_bin NOT NULL COMMENT '帐户名'",
	"int(10) DEFAULT '0' NOT NULL COMMENT '成交日期'",
	"int(10) DEFAULT '0' NOT NULL COMMENT '成交时间'",
	"char(2) DEFAULT '0' COLLATE utf8_bin NOT NULL COMMENT '买卖方向，  \"B\" (buy)表示买， \"S\" (sell)表示卖'",
	"varchar(16) COLLATE utf8_bin NOT NULL COMMENT '影子订单编号， 客户端显示使用'",
	"smallint(2) DEFAULT '0' NOT NULL COMMENT '开平标志，  1 表示开仓， 2 表示平仓， 3 表示平今'",
	"varchar(32) COLLATE utf8_bin NOT NULL COMMENT '交易所成交编号'",
	"varchar(16) COLLATE utf8_bin NOT NULL COMMENT '显示成交ID'",
	"smallint(2) NOT NULL COMMENT '昨仓标志， 0 表示今仓， 1表示昨仓'",
	"decimal(16,8) DEFAULT '0.00000000' NOT NULL COMMENT '持仓保证金,合约基币'",
	"decimal(16,8) DEFAULT '0.00000000' NOT NULL COMMENT '持仓保证金，系统基币'",
	"decimal(32,8) DEFAULT '0.00000000' NOT NULL COMMENT '上次结算价, 昨仓使用，为内盘'",
	"decimal(32,8) DEFAULT '0.00000000' NOT NULL COMMENT '今结算价，当日收盘后，为内盘'",
	"varchar(64) DEFAULT '0' COLLATE utf8_bin NOT NULL COMMENT '委托ID, 作成交信息时使用'",
	"varchar(64) COLLATE utf8_bin NOT NULL COMMENT '目标账户'",
};