#pragma once

enum SETTLE_USER_MONEY_INFO_TABLE_DESC : int {
	E_ID = 0,
	E_USERID,
	E_USERDEPOSIT,
	E_EQUIPMENT,
	E_PREBALANCE,
	E_CURRENTTOTAL,
	E_TODAYCLOSEPROFIT,
	E_TODAYFEE,
	E_TODAYINMONEY,
	E_TODAYOUTMONEY,
	E_HISTORYPROFIT,
	E_HISTORYFEE,
	E_HISTORYOUTMONEY,
	E_HISTORYINMONEY,
	E_FROZENMARGIN,
	E_HOLDMARGIN,
	E_POSITIONGAINLOSS,
	E_SETTLEGAINLOSS,
	E_SETTLEDATE,
	E_SETTLETIME,
	E_FROZENOUTMONEY,
	E_END
};

const char* const SETTLE_USER_MONEY_INFO_TABLE = "settle_user_money_info";

const char* const SETTLE_USER_MONEY_INFO_TABLE_COLS[E_END] = {
	"id",
	"userID",
	"userDeposit",
	"equipment",
	"preBalance",
	"currentTotal",
	"todayCloseProfit",
	"todayFee",
	"todayInMoney",
	"todayOutMoney",
	"historyProfit",
	"historyFee",
	"historyOutMoney",
	"historyInMoney",
	"frozenMargin",
	"holdMargin",
	"positionGainLoss",
	"settleGainLoss",
	"settleDate",
	"settleTime",
	"frozenOutMoney",
};

const char* const SETTLE_USER_MONEY_INFO_TABLE_COLS_ATTR[E_END] = {
	"int(8) unsigned NOT NULL",
	"varchar(64) COLLATE utf8_bin NOT NULL",
	"decimal(32,8) DEFAULT '0.00000000' NOT NULL COMMENT '用户保证金'",
	"decimal(32,8) DEFAULT '0.00000000' NOT NULL COMMENT '配置额度'",
	"decimal(32,8) DEFAULT '0.00000000' NOT NULL COMMENT '静态权益'",
	"decimal(32,8) DEFAULT '0.00000000' NOT NULL COMMENT '当前资金结余'",
	"decimal(32,8) DEFAULT '0.00000000' NOT NULL COMMENT '当日平仓盈亏'",
	"decimal(32,8) DEFAULT '0.00000000' NOT NULL COMMENT '当日手续费'",
	"decimal(32,8) DEFAULT '0.00000000' NOT NULL COMMENT '当日入金'",
	"decimal(32,8) DEFAULT '0.00000000' NOT NULL COMMENT '当如出金'",
	"decimal(32,8) DEFAULT '0.00000000' NOT NULL COMMENT '历史盈亏总和'",
	"decimal(32,8) DEFAULT '0.00000000' NOT NULL COMMENT '历史手续费总和'",
	"decimal(32,8) DEFAULT '0.00000000' NOT NULL COMMENT '历史出金总和'",
	"decimal(32,8) DEFAULT '0.00000000' NOT NULL COMMENT '历史入金总和'",
	"decimal(32,8) DEFAULT '0.00000000' NOT NULL COMMENT '冻结保证金'",
	"decimal(32,8) DEFAULT '0.00000000' NOT NULL COMMENT '持仓保证金'",
	"decimal(32,8) NOT NULL COMMENT '浮动盈亏'",
	"decimal(32,8) DEFAULT '0.00000000' NOT NULL COMMENT '盯市盈亏'",
	"int(8) DEFAULT '-1' NOT NULL",
	"int(8) DEFAULT '-1' NOT NULL",
	"decimal(32,8) DEFAULT '0.00000000' NOT NULL COMMENT '冻结资金'",
};