#pragma once

enum STOP_PROFIT_LOSS_HISTORY_ORDERS_TABLE_DESC : int {
	E_STPRLOHIOR_STOPLOSSID = 0,
	E_STPRLOHIOR_USERID,
	E_STPRLOHIOR_CONTRACTID,
	E_STPRLOHIOR_TRIGGERTYPE,
	E_STPRLOHIOR_TRIGGERLOSSPRICE,
	E_STPRLOHIOR_TRIGGERPROFITPRICE,
	E_STPRLOHIOR_TIMECONDITIONTYPE,
	E_STPRLOHIOR_ORDERTYPE,
	E_STPRLOHIOR_DIRECTION,
	E_STPRLOHIOR_VOLUME,
	E_STPRLOHIOR_PRICE,
	E_STPRLOHIOR_STATE,
	E_STPRLOHIOR_STOPPROFITLOSSSTYLE,
	E_STPRLOHIOR_ORDERFROM,
	E_STPRLOHIOR_CREATEDATE,
	E_STPRLOHIOR_CREATETIME,
	E_STPRLOHIOR_UPDATEDATE,
	E_STPRLOHIOR_UPDATETIME,
	E_STPRLOHIOR_IP,
	E_STPRLOHIOR_MAC,
	E_STPRLOHIOR_ORDERID,
	E_STPRLOHIOR_FLOTLOSS,
	E_STPRLOHIOR_STOPPROFITLOSSTYPE,
	E_STPRLOHIOR_ORDERADDPRICE,
	E_STPRLOHIOR_LASTPRICE,
	E_STPRLOHIOR_END
};

const char* const STOP_PROFIT_LOSS_HISTORY_ORDERS_TABLE = "stop_profit_loss_history_orders";

const char* const STOP_PROFIT_LOSS_HISTORY_ORDERS_TABLE_COLS[E_STPRLOHIOR_END] = {
	"stopLossID",
	"userID",
	"contractID",
	"triggerType",
	"triggerLossPrice",
	"triggerProfitPrice",
	"timeConditionType",
	"orderType",
	"direction",
	"volume",
	"price",
	"state",
	"stopProfitLossStyle",
	"orderFrom",
	"createDate",
	"createTime",
	"updateDate",
	"updateTime",
	"ip",
	"mac",
	"orderID",
	"flotLoss",
	"stopProfitLossType",
	"orderAddPrice",
	"lastPrice",
};

const char* const STOP_PROFIT_LOSS_HISTORY_ORDERS_TABLE_COLS_ATTR[E_STPRLOHIOR_END] = {
	"varchar(64) COLLATE latin1_swedish_ci NOT NULL",
	"varchar(64) COLLATE latin1_swedish_ci NOT NULL",
	"varchar(64) COLLATE latin1_swedish_ci NOT NULL",
	"tinyint(2) NOT NULL COMMENT '触发类型：1最新价 2对手价'",
	"decimal(16,8) DEFAULT '0.00000000' NOT NULL",
	"decimal(16,8) DEFAULT '0.00000000' NOT NULL",
	"tinyint(2) NOT NULL COMMENT '时间有效类型，0当日有效，1交割日前有效'",
	"tinyint(2) NOT NULL COMMENT '下单类型：1指定价（下单限价）2对手价（下单限价）3市价（下单市价）'",
	"char(2) COLLATE latin1_swedish_ci NOT NULL COMMENT '买卖方向，  \"B\" (buy)表示买， \"S\" (sell)表示卖'",
	"int(4) NOT NULL",
	"decimal(16,8) DEFAULT '0.00000000' NOT NULL COMMENT '指定价有效'",
	"tinyint(2) DEFAULT '0' NOT NULL COMMENT '止盈止损单状态：0 新建（工作中）1已触发（已发委托）2失败3删除'",
	"smallint(2) DEFAULT '0'",
	"tinyint(2) NOT NULL COMMENT '下单来源'",
	"int(10) NOT NULL",
	"int(10) NOT NULL",
	"int(10) DEFAULT '-1' NOT NULL",
	"int(10) DEFAULT '-1' NOT NULL",
	"varchar(32) COLLATE latin1_swedish_ci NOT NULL",
	"varchar(64) COLLATE latin1_swedish_ci NOT NULL",
	"varchar(64) COLLATE latin1_swedish_ci NOT NULL COMMENT '内部使用'",
	"decimal(16,8) COMMENT '浮动止损价位'",
	"int(2) DEFAULT '0' COMMENT '止盈止损类型   0 无浮动止损，1 有浮动止损，2自动止盈止损'",
	"decimal(16,8) DEFAULT '0.00000000' COMMENT '下单追价'",
	"decimal(16,8) COMMENT '最新价'",
};