#pragma once

enum TRADE_INFO_TABLE_DESC : int {
	E_TRIN_TRADEID = 0,
	E_TRIN_POSITIONID,
	E_TRIN_USERID,
	E_TRIN_CONTRACTID,
	E_TRIN_VOLUME,
	E_TRIN_CLOSEPROFIT,
	E_TRIN_TRADEPRICE,
	E_TRIN_CONTRACTNAME,
	E_TRIN_ACCOUNTNAME,
	E_TRIN_GENERATEDATE,
	E_TRIN_GENERATETIME,
	E_TRIN_DIRECTION,
	E_TRIN_SHADOWORDERID,
	E_TRIN_FEE,
	E_TRIN_CONTRACTFEE,
	E_TRIN_PRICETYPE,
	E_TRIN_OPENOFFSET,
	E_TRIN_EXCHANGETRADEID,
	E_TRIN_SHADOWTRADEID,
	E_TRIN_TURNOVER,
	E_TRIN_ORDERID,
	E_TRIN_TARGETUSERID,
	E_TRIN_CURRENCY,
	E_TRIN_END
};

const char* const TRADE_INFO_TABLE = "trade_info";

const char* const TRADE_INFO_TABLE_COLS[E_TRIN_END] = {
	"tradeID",
	"positionID",
	"userID",
	"contractID",
	"volume",
	"closeProfit",
	"tradePrice",
	"contractName",
	"accountName",
	"generateDate",
	"generateTime",
	"direction",
	"shadowOrderID",
	"fee",
	"contractFee",
	"priceType",
	"openOffset",
	"exchangeTradeID",
	"shadowTradeID",
	"turnOver",
	"orderID",
	"targetUserID",
	"currency",
};

const char* const TRADE_INFO_TABLE_COLS_ATTR[E_TRIN_END] = {
	"varchar(64) COLLATE utf8_bin NOT NULL",
	"varchar(64) COLLATE utf8_bin NOT NULL COMMENT '平仓对应的持仓ID'",
	"varchar(64) DEFAULT '0' COLLATE utf8_bin NOT NULL COMMENT '帐户标识（用户ID)， 系统内部使用'",
	"varchar(64) DEFAULT '0' COLLATE utf8_bin NOT NULL COMMENT '合约ID'",
	"int(10) DEFAULT '0' NOT NULL COMMENT '成交手数'",
	"decimal(32,8) DEFAULT '0.00000000' NOT NULL COMMENT '平仓盈亏，单位为基币'",
	"decimal(32,8) DEFAULT '0.00000000' NOT NULL COMMENT '成交价格'",
	"varchar(16) COLLATE utf8_bin NOT NULL COMMENT '合约名'",
	"varchar(32) COLLATE utf8_bin NOT NULL COMMENT '帐户名'",
	"int(10) DEFAULT '0' NOT NULL COMMENT '成交日期'",
	"int(10) DEFAULT '0' NOT NULL COMMENT '成交时间'",
	"char(2) DEFAULT '0' COLLATE utf8_bin NOT NULL COMMENT '买卖方向，  \"B\" (buy)表示买， \"S\" (sell)表示卖'",
	"varchar(16) COLLATE utf8_bin NOT NULL COMMENT '影子订单编号， 客户端显示使用'",
	"decimal(16,8) NOT NULL COMMENT '系统基币手续费'",
	"decimal(16,8) DEFAULT '0.00000000' NOT NULL COMMENT '合约基币手续费'",
	"char(2) COLLATE utf8_bin NOT NULL",
	"smallint(2) DEFAULT '0' NOT NULL COMMENT '开平标志，  1 表示开仓， 2 表示平仓， 3 表示平今'",
	"varchar(32) COLLATE utf8_bin NOT NULL COMMENT '交易所成交编号'",
	"varchar(16) COLLATE utf8_bin NOT NULL COMMENT '显示成交ID'",
	"decimal(32,8) DEFAULT '0.00000000' NOT NULL COMMENT '成交额'",
	"varchar(64) DEFAULT '0' COLLATE utf8_bin NOT NULL COMMENT '委托ID, 作成交信息时使用'",
	"varchar(64) COLLATE utf8_bin NOT NULL COMMENT '目标账户'",
	"varchar(4) COLLATE utf8_bin NOT NULL COMMENT '币种'",
};